import unittest
from test import *
import test

# Appends the test suites generated by the suite() function of all public modules
# in the test package.
def suite():
  return unittest.TestSuite([getattr(test, module).suite() for module in test.__all__])
