"""
Unit test module.

The unit tests themselves are stored in the 'test' subdirectory. This module is
a simple shim that hooks them into Django's testing framework.
"""
import unittest

from test import *
import test

def suite():
    """
    Appends the test suites generated by the suite() function of all public
    modules in the test package.
    """
    return unittest.TestSuite([getattr(test, module).suite()
                                 for module in test.__all__])
